---
name: Workflow

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        db-backend: [sqlite, mysql, postgresql]
        target:
          - x86_64-unknown-linux-gnu
          # - x86_64-unknown-linux-musl
          # - x86_64-apple-darwin
          # - x86_64-pc-windows-msvc
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            ext:
          # - target: x86_64-unknown-linux-musl
          #   os: ubuntu-latest
          #   ext:
          # - target: x86_64-apple-darwin
          #   os: macOS-latest
          #   ext:
          # - target: x86_64-pc-windows-msvc
          #   os: windows-latest
          #   ext: .exe
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1

    - name: Create assets
      run: |
        mkdir -p target/${{ matrix.target }}/release
        echo "This is the asset content for bitwarden_rs-${{ matrix.db-backend }}-${{ matrix.target }}${{ matrix.ext }}" | tee target/${{ matrix.target }}/release/bitwarden_rs${{ matrix.ext }}

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: bitwarden_rs-${{ matrix.db-backend }}-${{ matrix.target }}${{ matrix.ext }}
        path: target/${{ matrix.target }}/release/bitwarden_rs${{ matrix.ext }}

  prepare-release:
    name: Prepare release
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Create Pre-Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: true

    - uses: actions/download-artifact@v2
      with:
        name: bitwarden_rs-postgresql-x86_64-unknown-linux-gnu

    - name: Upload Release Assets
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        # TODO: Use build matrix
        asset_path: bitwarden_rs-postgresql-x86_64-unknown-linux-gnu
        asset_name: bitwarden_rs-postgresql-x86_64-unknown-linux-gnu
        asset_content_type: application/octet-stream

#   upload-release-assets:
#     name: Upload release assets
#     if: startsWith(github.ref, 'refs/tags/')
#     needs: [build, prepare-release]
#     strategy:
#       fail-fast: false
#       matrix:
#         db-backend: [sqlite, mysql, postgresql]
#         target:
#           - x86_64-unknown-linux-gnu
#           # - x86_64-unknown-linux-musl
#           # - x86_64-apple-darwin
#           # - x86_64-pc-windows-msvc
#         include:
#           - target: x86_64-unknown-linux-gnu
#             os: ubuntu-latest
#             ext:
#           # - target: x86_64-unknown-linux-musl
#           #   os: ubuntu-latest
#           #   ext:
#           # - target: x86_64-apple-darwin
#           #   os: macOS-latest
#           #   ext:
#           # - target: x86_64-pc-windows-msvc
#           #   os: windows-latest
#           #   ext: .exe
#     runs-on: ${{ matrix.os }}
#     steps:
#     - name: Upload Release Assets
#       id: upload-release-asset 
#       uses: actions/upload-release-asset@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         upload_url: ${{ steps.create_release.outputs.upload_url }}
#         asset_path: target/${{ matrix.target }}/release/bitwarden_rs${{ matrix.ext }}
#         asset_name: bitwarden_rs-${{ matrix.db-backend }}-${{ matrix.target }}${{ matrix.ext }}
#         asset_content_type: application/octet-stream
